stages:
  - test
  - bundle
  - build
  - deploy
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml

.deploy-template:
  image: registry.gitlab.alt.coop/ctrlaltcoop/deployment-toolchain:0-0-3
  before_script:
    - kubectl create secret docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run=client | kubectl apply -f -
    - cd kustomize/base
    - envsubst < add-gitlab-annotations.template.yaml > add-gitlab-annotations.yaml
    - cd ../../

lint:
  image: node:16-alpine
  stage: test
  script:
    - npm ci
    - npm run lint
  cache:
    paths:
      - node_modules/

.bundle:
  image: node:16-alpine
  stage: bundle
  before_script:
    - apk update && apk add git
  script:
    - npm ci
    - npm run build -- -m pwa
  cache:
    paths:
      - node_modules/
  environment:
    action: prepare
    name: staging
  artifacts:
    paths:
      - dist/

bundle-staging:
  extends: .bundle
  environment:
    action: prepare
    name: staging
  only:
    - main

bundle-development:
  extends: .bundle
  environment:
    action: prepare
    name: development
  only:
    - develop

bundle-review:
  extends: .bundle
  environment:
    action: prepare
    name: review/$CI_COMMIT_REF_SLUG
  except:
    - main
    - develop

.android:
  image: circleci/android:api-30-node
  stage: bundle
  before_script:
    - sudo npm install -g npm@^7
  script:
    - sudo npm ci
    - npx quasar build -m capacitor -T android
    - cd src-capacitor/android
    - ./gradlew bundleRelease
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - src-capacitor/android/app/build/

android-development:
  extends: .android
  environment:
    action: prepare
    name: development
  only:
    - branches
  except:
    - tags
    - main

android-staging:
  extends: .android
  environment:
    action: prepare
    name: staging
  only:
    - main

android-production:
  extends: .android
  environment:
    action: prepare
    name: production
  only:
    - tags

.ios:
  stage: bundle
  script:
    - sudo npm ci
    - npx quasar build -m capacitor -T ios
  tags:
    - macos
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - src-capacitor/ios/App/


ios-development:
  extends: .ios
  environment:
    action: prepare
    name: development
  only:
    - branches
  except:
    - tags
    - main

ios-staging:
  extends: .ios
  environment:
    action: prepare
    name: staging
  only:
    - main

ios-production:
  extends: .ios
  environment:
    action: prepare
    name: production
  only:
    - tags





staging:
  extends: .deploy-template
  stage: deploy
  script:
    - cd kustomize/staging
    - kustomize edit set image $CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    - kustomize edit set namespace $KUBE_NAMESPACE
    - kustomize build | kubectl apply -f -
  only:
    - main
  environment:
    name: staging
    url: https://staging.wk-frontend.haze.alt.coop

development:
  extends: .deploy-template
  stage: deploy
  script:
    - cd kustomize/development
    - kustomize edit set image $CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    - kustomize edit set namespace $KUBE_NAMESPACE
    - kustomize build | kubectl apply -f -
  only:
    - develop
  environment:
    name: development
    url: https://development.wk-frontend.haze.alt.coop

review:
  extends: .deploy-template
  stage: deploy
  script:
    - cd kustomize/review
    - export INGRESS_HOST=$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    - envsubst < ingress-override.template.yaml > ingress-override.yaml
    - kustomize edit set image $CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    - kustomize edit set namespace $KUBE_NAMESPACE
    - kustomize build # print to stdout to debug
    - kustomize build > out.yaml
    - kubectl apply -f out.yaml
  except:
    - main
    - develop
    - tags
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review
  artifacts:
    paths: [ kustomize/review/out.yaml ]

stop_review:
  stage: cleanup
  extends: .deploy-template
  variables:
    GIT_STRATEGY: none
  script:
    - kubectl delete -f ./kustomize/review/out.yaml
  when: manual
  except:
    - main
    - develop
    - tags
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop

