variables:
  POSTGRES_ENABLED: "false"
  ROLLOUT_RESOURCE_TYPE: deployment
  MIGRATE_HELM_2TO3: "true"
  AUTO_DEVOPS_FORCE_DEPLOY_V2: 1


include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
  - template: Jobs/Helm-2to3.gitlab-ci.yml

stages:
  - test
  - bundle
  - build
  - review
  - staging
  - canary
  - deploy
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - production
  - cleanup

lint:
  image: node:16-alpine
  stage: test
  script:
    - npm ci
    - npm run lint
  cache:
    paths:
      - node_modules/

bundle-staging:
  image: node:16-alpine
  stage: bundle
  script:
    - npm ci
    - npm run build -- -m pwa
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
