server {
  listen 5000 default_server;
  listen [::]:5000 default_server;
  root /opt/bitnami/nginx/html/;
  location / {
      try_files $uri $uri/ /index.html;
  }

  location /service-worker.js {
    add_header Cache-Control "no-cache";
  }

  index index.htm index.html;
}
